# Site settings
title: attah.net
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is attah.net
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://attah.net" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#hackaday_username: attah
github_username:  attah

# Build settings
markdown: kramdown
